apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-numbers
spec:
  selector:
    matchLabels:
      app: prime-numbers
  replicas: 1
  template:
    metadata:
      labels:
        app: prime-numbers
    spec:
      serviceAccountName: pod-controller-sa
      containers:
        - name: prime-numbers
          image: systemautoscaler/prime-numbers:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
        - name: proxy-vertical-scaling #aa
          image: quintero98/proxy-vertical-scaling:v4 #nginx:1.25.1 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 150Mi
              cpu: 250m
            limits:
              memory: 150Mi
              cpu: 250m
