apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-numbers
spec:
  selector:
    matchLabels:
      app: prime-numbers
  replicas: 2
  template:
    metadata:
      labels:
        app: prime-numbers
        logger: "on"
    spec:
      serviceAccountName: pod-controller-sa
      containers:
        - name: prime-numbers
          image: systemautoscaler/prime-numbers:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
        - name: proxy-vertical-scaling #aa
          image: quintero98/proxy-vertical-scaling:v0.1_threading #v6 #nginx:1.25.1
          imagePullPolicy: Always
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NS_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_DP_NAME
            value: prime-numbers # Must be changed manually
          - name: MY_APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          - name: CONTAINER_TO_FORWARD
            value: prime-numbers  
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 150Mi
              cpu: 250m
            limits:
              memory: 150Mi
              cpu: 250m

        - name: metrics-logger
          image: quintero98/metrics-logger:dev
          imagePullPolicy: Always
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_NS_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_DP_NAME
            value: prime-numbers # Must be changed manually
          - name: MY_APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          - name: CONTAINER_TO_FORWARD
            value: prime-numbers
          resources:
            requests:
              memory: 150Mi
              cpu: 250m
            limits:
              memory: 150Mi
              cpu: 250m
          volumeMounts:
          - name: persistent-storage
            mountPath: /data 
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: mypvc
