apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-numbers
spec:
  selector:
    matchLabels:
      app: prime-numbers
  replicas: 1
  template:
    metadata:
      labels:
        app: prime-numbers
    spec:
      serviceAccountName: pod-controller-sa
      containers:
        - name: prime-numbers
          image: systemautoscaler/prime-numbers:dev #nginx:1.25.1 #
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resizePolicy:
            - resourceName: cpu
              restartPolicy: RestartContainer
            - resourceName: memory
              restartPolicy: RestartContainer
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 250m
      
